// Code generated by "stringer -type=parseState"; DO NOT EDIT

package main

import "fmt"

const _parseState_name = "stateNonestateIdentifierstateOperatorstateStringSinglestateStringDoublestateStringEscapestateBracestateParenstateArraystateCommentStartstateCommentEndstateCommentstateCommentBlock"

var _parseState_index = [...]uint8{0, 9, 24, 37, 54, 71, 88, 98, 108, 118, 135, 150, 162, 179}

func (i parseState) String() string {
	if i < 0 || i >= parseState(len(_parseState_index)-1) {
		return fmt.Sprintf("parseState(%d)", i)
	}
	return _parseState_name[_parseState_index[i]:_parseState_index[i+1]]
}
